/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	/*
	// Task: Load two values from memory, add them and store the result back to the memory using inline assembly statements.
	__asm volatile("LDR R1, =#0x20001000");
	__asm volatile("LDR R2, =#0x20001004");

	__asm volatile("LDR R0, [R1]");
	__asm volatile("LDR R1, [R2]");

	__asm volatile("ADD R0, R0, R1");

	__asm volatile("STR R0, [R2]");
	*/

	/*
	// Task: Move the content of "C" variable "val" to ARM register "R0".
	int32_t val = 20;

	__asm volatile("MOV R0, %0" : : "r"(val));
	*/

	/*
	// TasK: Move the content of "CONTROL" register to "C" variable “control_reg”.
	uint32_t control_reg;

	__asm volatile("MRS %0, CONTROL" : "=r"(control_reg));
	*/

	/*
	// Task: Copy the content of "C" variable "var1" to "var2".
	int32_t var1 = 50, var2;

	__asm volatile("MOV %0, %1" : "=r"(var2) : "r"(var1));
	*/

	/*
	// Task: Copy the contents of a pointer into another variable
	int32_t var1, *var2;
	var2 = (int32_t*)0x20000008;

	__asm volatile("LDR %0, [%1]" : "=r"(var1) : "r"(var2));
	*/

    /* Loop forever */
	for(;;);
}
