/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

extern void initialise_monitor_handles(void);

void change_access_level_to_NPAL(void);
void generate_interrupt(void);

void HardFault_Handler(void);
void RTC_WKUP_IRQHandler(void);

int main(void)
{
	initialise_monitor_handles();

	printf("Thread mode: before interrupt\n");

	// Change access level to non privileged access level(NPAl)
	change_access_level_to_NPAL();

	generate_interrupt();

	printf("Thread mode: after interrupt\n");

    /* Loop forever */
	for(;;);
}

void change_access_level_to_NPAL(void){
	// Read
	__asm volatile("MRS R0, CONTROL");
	// Modify
	__asm volatile("ORR R0, R0, #0X01");
	// Write
	__asm volatile("MSR CONTROL, R0");
}

void generate_interrupt(void){
	uint32_t *pISER0 = (uint32_t*) 0xE000E100;
	uint32_t *pSTIR = (uint32_t*) 0xE000EF00;

	// Enable IRQ3 Interrupt
	*pISER0 |= (1 << 3);

	// Generate an software interrupt for IRQ3
	*pSTIR = (3 & 0x1FF);
}

void HardFault_Handler(void){
	printf("Hard fault detected! \n");
	while(1);
}

void RTC_WKUP_IRQHandler(void){
	printf("Handler mode: ISR\n");
}
