/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

extern void initialise_monitor_handles(void);

__attribute__((naked))
void changeSPToPSP(void);

void generateException(void);
void SVC_Handler(void);

int32_t add(int32_t a, int32_t b, int32_t c);

int main(void)
{
	initialise_monitor_handles();

	changeSPToPSP();

	int32_t addResult = 0;

	addResult = add(5, 12, -1);

	printf("Addition operation result: %ld\n", addResult);

	generateException(); // Program mode will be change to "Handler" mode, and "SP" automatically will be change to "MSP"

    /* Loop forever */
	for(;;);
}

__attribute__((naked))
void changeSPToPSP(void){
	// Calculate "PSP" Start Address
	__asm volatile(
			".equ SRAM_END, (0x20000000 + (128 * 1024))\n\t"
			".equ PSP_START, (SRAM_END - 512)\n\t"
	);

	// Store "PSP_START" into "PSP" register
	__asm volatile(
			"LDR R0, =PSP_START\n\t"
			"MSR PSP, R0\n\t"
	);

	// Set 1th-bit of "CONTROL" register, to activate "PSP" as "SP"
	__asm volatile(
			"MOV R0, #0x2\n\t"
			"MSR CONTROL, R0\n\t"
	);

	// Return the program to the main function
	__asm volatile("BX LR");
}

void generateException(void){
	// Execute "SVC" instruction to cause "SVC" exception
	__asm volatile("SVC #0x2");
}

void SVC_Handler(void){
	printf("SVC_Handler executed!\n");
}

int32_t add(int32_t a, int32_t b, int32_t c){
	return (a + b + c);
}
