/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

extern void initialise_monitor_handles(void);

void HardFault_Handler(void);

int main(void)
{
	initialise_monitor_handles();

	void (*fun_ptr)(void);
	fun_ptr = (void*)0x08000204;

	/*
	* When the function pointer is called, the target address is loaded into
	* the Program Counter (PC). On ARM Cortex-M processors, bit 0 of the
	* target address indicates the Thumb state and must be set to 1.
	*
	* Since bit 0 of 0x08000204 is 0, the target address does not indicate
	* Thumb state. Because ARM Cortex-M processors support only the Thumb
	* instruction set, this results in an invalid state and causes a fault.
	*/
	fun_ptr();

    /* Loop forever */
	for(;;);
}

void HardFault_Handler(void){
	printf("Hard fault detected! \n");
	while(1);
}
