/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

extern void initialise_monitor_handles(void);

// Implemented functions
int32_t add(int32_t x, int32_t y);
int32_t sub(int32_t x, int32_t y);
int32_t mul(int32_t x, int32_t y);
int32_t div(int32_t x, int32_t y);

// Handlers
void SVC_Handler(void);
void SVC_Handler_c(uint32_t *pBaseStackFrame);

int main(void)
{
	initialise_monitor_handles();

	int32_t result = 0;

	result = add(12, -3);
	printf("Addition operation result: %ld\n", result);

	result = sub(60, 34);
	printf("Subtraction operation result: %ld\n", result);

	result = mul(5, 75);
	printf("Multiplication operation result: %ld\n", result);

	result = div(128, 4);
	printf("Division operation result: %ld\n", result);

    /* Loop forever */
	for(;;);
}

// Implemented functions
int32_t add(int32_t x, int32_t y){
	int32_t result = 0;

	__asm volatile("SVC #36");

	// Extract operation result
	__asm volatile("MOV %0, R0" : "=r"(result) :);

	return result;
}

int32_t sub(int32_t x, int32_t y){
	int32_t result = 0;

	__asm volatile("SVC #37");

	// Extract operation result
	__asm volatile("MOV %0, R0" : "=r"(result) :);

	return result;
}

int32_t mul(int32_t x, int32_t y){
	int32_t result = 0;

	__asm volatile("SVC #38");

	// Extract operation result
	__asm volatile("MOV %0, R0" : "=r"(result) :);

	return result;
}

int32_t div(int32_t x, int32_t y){
	int32_t result = 0;

	__asm volatile("SVC #39");

	// Extract operation result
	__asm volatile("MOV %0, R0" : "=r"(result) :);

	return result;
}

// Handlers
__attribute__((naked))
void SVC_Handler(void){
	__asm("MRS R0, MSP");
	__asm("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBaseStackFrame){
	uint8_t *pReturnAddr = (uint8_t*) pBaseStackFrame[6];

	// Decrement the return address to point to "opcode" of the "SVC" instruction in the program memory.
	pReturnAddr -= 2;

	// Extract "SVC" number.
	uint8_t SVCNumber = *pReturnAddr;

	int32_t result = 0;

	switch (SVCNumber) {
		case 36:
			result = (pBaseStackFrame[0] + pBaseStackFrame[1]);
			break;
		case 37:
			result = (pBaseStackFrame[0] - pBaseStackFrame[1]);
			break;
		case 38:
			result = (pBaseStackFrame[0] * pBaseStackFrame[1]);
			break;
		case 39:
			result = (pBaseStackFrame[0] / pBaseStackFrame[1]);
			break;
		default:
			printf("Invalid SVC(operation) code!\n");
			break;
	}

	pBaseStackFrame[0] = result;
}
