/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

extern void initialise_monitor_handles(void);

// Handlers
void SVC_Handler(void);
void SVC_Handler_c(uint32_t *pBaseStackFrame);

int main(void)
{
	initialise_monitor_handles();

	// 1. Execute "SVC" Instruction with an argument.
	__asm volatile("SVC #0x5");

	// Get incremented "SVC" number and print it.
	uint32_t newSVCNumber;

	__asm volatile("MOV %0, R0" : "=r"(newSVCNumber) : );

	printf("SVC number incremented to \'%lu\'\n", newSVCNumber);

    /* Loop forever */
	for(;;);
}

// 2. Implement "SVC" handler.
__attribute__((naked))
void SVC_Handler(void){
	__asm("MRS R0, MSP");
	__asm("B SVC_Handler_c");
}

// 3. Extract "SVC" number and print it.
void SVC_Handler_c(uint32_t *pBaseStackFrame){
	uint8_t *pReturnAddr = (uint8_t*) pBaseStackFrame[6];

	// Decrement the return address to point to "opcode" of the "SVC" instruction in the program memory.
	pReturnAddr -= 2;

	// Extract "SVC" number.
	uint8_t SVCNumber = *pReturnAddr;

	printf("Extracted SVC number: %u\n", SVCNumber);

	// 4. Increment the "SVC" number and return it to thread mode.
	SVCNumber += 4;

	pBaseStackFrame[0] = SVCNumber;
}
