/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

extern void initialise_monitor_handles(void);

#define NVIC_ISPR1_ADDR 0xE000E204U
#define NVIC_ISER1_ADDR 0xE000E104U

#define USART2_IRQNO 38U

void USART2_IRQHandler(void);

int main(void)
{
	initialise_monitor_handles();

	// 1. Manually pend the pending bit for the USART2 IRQ number in NVIC
	uint32_t *pISPR1 = (uint32_t*) NVIC_ISPR1_ADDR;

	*pISPR1 |= (1 << (USART2_IRQNO % 32));

	// 2. Enable the USART2 IRQ number in NVIC
	uint32_t *pISER1 = (uint32_t*) NVIC_ISER1_ADDR;

	*pISER1 |= (1 << (USART2_IRQNO % 32));

    /* Loop forever */
	for(;;);
}

void USART2_IRQHandler(void){
	printf("USART2 ISR Executed.\n");
}
