/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define BYTE_ADDRESS		0x20000200U
#define BIT_BAND_BASE 		0x20000000U
#define BIT_BAND_ALIAS_BASE 0x22000000U

#define ALIAS_ADDRESS(byteAddress) ((BIT_BAND_ALIAS_BASE) + (((byteAddress) - (BIT_BAND_BASE)) * 32) + (7 * 4)) // Mapping formula: bit_word_addr = bit_band_base + (byte_offset x 32) + (bit_number × 4)

int main(void)
{
	uint8_t *ptr = (uint8_t*)BYTE_ADDRESS;

	*ptr = 0xFF;

	// Normal method
	*ptr &= ~(1 << 7);

	// Reset pointer value to "0xFF"
	*ptr = 0xFF;

	// Bit banding method
	uint8_t *aliasAddress = (uint8_t*) ALIAS_ADDRESS(BYTE_ADDRESS);

	// Reset 7th-bit position
	*aliasAddress = 0;

    /* Loop forever */
	for(;;);
}
