/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#define NVIC_IPR_BASE_ADDR 	0xE000E400U
#define NVIC_ISPR0_ADDR		0XE000E200U
#define NVIC_ISER0_ADDR		0xE000E100U

#define TIM2_IRQNO 28
#define I2C1_IRQNO 31

extern void initialise_monitor_handles(void);

// Implemented functions
void configureIRQInterruptLevel(uint8_t IRQNO, uint8_t interruptLevel);

// Handlers
void TIM2_IRQHandler(void);
void I2C1_EV_IRQHandler(void);

// Global variables
uint32_t *pNVIC_IPRBase = (uint32_t*) NVIC_IPR_BASE_ADDR;
uint32_t *pNVIC_ISPR0 = (uint32_t*) NVIC_ISPR0_ADDR;
uint32_t *pNVIC_ISER0 = (uint32_t*) NVIC_ISER0_ADDR;

int main(void)
{
	initialise_monitor_handles();

	// 1. Configure peripherals interrupt level
	configureIRQInterruptLevel(TIM2_IRQNO, 0x80);
	configureIRQInterruptLevel(I2C1_IRQNO, 0x70);

	// 2. Set the peripherals interrupt bit pending
	*pNVIC_ISPR0 |= (1 << TIM2_IRQNO);

	// 3. Enable the IRQs
	*pNVIC_ISER0 |= (1 << I2C1_IRQNO);
	*pNVIC_ISER0 |= (1 << TIM2_IRQNO);

    /* Loop forever */
	for(;;);
}

void configureIRQInterruptLevel(uint8_t IRQNO, uint8_t interruptLevel){
	// 1. Find IPRx
	uint32_t *IPRx = (pNVIC_IPRBase + (IRQNO / 4));

	// 2. Find IRQ position in IPRx
	uint8_t pos = ((IRQNO % 4) * 8);

	// 3. Configure the interrupt level
	*IPRx &= ~(0xFF << pos); 			// Clear
	*IPRx |= (interruptLevel << pos); 	// Set
}

void TIM2_IRQHandler(void){
	printf("--- TIM2_IRQHandler ---\n");

	// Set the "I2C1_EV" interrupt bit pending manually
	*pNVIC_ISPR0 |= (1 << I2C1_IRQNO);

	while(1);
}

void I2C1_EV_IRQHandler(void){
	printf("--- I2C1_EV_IRQHandler ---\n");
}
