/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#define SHCRS_ADDR 	0xE000ED24U
#define UFSR_ADDR 	0xE000ED2AU

extern void initialise_monitor_handles(void);

// Handlers
void HardFault_Handler(void);
void MemManage_Handler(void);
void BusFault_Handler(void);
void UsageFault_Handler(void);
void UsageFault_Handler_c(uint32_t *pBaseStackFrame);

int main(void)
{
	initialise_monitor_handles();

	// 1. Enable "UsageFault", "BusFault" and "MemManage" exceptions in "SHCRS" register.
	uint32_t *pSHCRS = (uint32_t*) SHCRS_ADDR;

	*pSHCRS |= (7 << 16);

	// 3. Force the processor to execute an undefined instruction.
	uint32_t *pSRAM = (uint32_t*) 0x20010000;

	*pSRAM = 0xFFFFFFFF;

	void (*some_address) (void);

	some_address = (void*) pSRAM;

	some_address();

    /* Loop forever */
	for(;;);
}

// 2. Implement the fault handlers

void HardFault_Handler(void){
	printf("HardFault exception!\n");
	while(1);
}

void MemManage_Handler(void){
	printf("MemManage exception!\n");
	while(1);
}

void BusFault_Handler(void){
	printf("BusFault exception!\n");
	while(1);
}

__attribute__((naked))
void UsageFault_Handler(void){
	__asm("MRS R0, MSP");
	__asm("B UsageFault_Handler_c");
}

void UsageFault_Handler_c(uint32_t *pBaseStackFrame){
	uint32_t *pUFSR = (uint32_t*) UFSR_ADDR;

	printf("UsageFault exception!\n");
	printf("UFSR: %lx\n", (*pUFSR) & 0xFFFF);

	printf("pBaseStackFrame: %p\n", pBaseStackFrame);
	printf("Value of R0: %lx\n", pBaseStackFrame[0]);
	printf("Value of R1: %lx\n", pBaseStackFrame[1]);
	printf("Value of R2: %lx\n", pBaseStackFrame[2]);
	printf("Value of R3: %lx\n", pBaseStackFrame[3]);
	printf("Value of R12: %lx\n", pBaseStackFrame[4]);
	printf("Value of LR: %lx\n", pBaseStackFrame[5]);
	printf("Value of PC: %lx\n", pBaseStackFrame[6]);
	printf("Value of xPSR: %lx\n", pBaseStackFrame[7]);

	while(1);
}
